### PR TITLE
Simplify cloning of a vacancy

### PR DESCRIPTION
**Pull request by sachpatel**

### CODE REVIEW

**Comment by leewadhams** [comment]
I see why you've done it, and I originally started doing this, but it doesn't feel right/safe to do this. We change what the vacancy reference points to completely which could be cause issue if you want to do anything with the original vacancy afterwards e.g. log messages. 

If you guys are happy with it then I will certainly get over it ;-)

**Comment by chrisjensenuk** [comment]
@leewadhams I agree with your concerns. My preference is for creating a new object.

**Comment by sachpatel** [comment]
This should all point to 👉  @mgwilliam . Let's discuss when we are all in office. The most suitable approach might be to map it into a new vacancy.

**Comment by sachpatel** [comment]
Closing because of the discussion had.

**Pull request closed without merging**
